default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: railway
  username: postgres
  password: 2sI8r56qScm3GQSXeOUy
  host: containers-us-west-31.railway.app
  port: 7347
  pool: 5
